### ISSUE TITLE
GitHub App Logo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/library#84]
The App Logo is one of the _first_ things people interact with when using the Library App.

Visiting https://dwyl-library.herokuapp.com we see this nice home screen with two titles:
![image](https://user-images.githubusercontent.com/194400/60159350-e0baf100-97ea-11e9-8458-9b248aa7debf.png)

Clicking/taping on "**login**" button leads to a GitHub Auth page:
![image](https://user-images.githubusercontent.com/194400/60159434-13fd8000-97eb-11e9-88ee-26c4b05e7aa9.png)

dwyl-library by [dwyl](https://github.com/dwyl) ... the space invader logo ("alien monster") 👾does not inspire confidence ...

# Story

As a first-time user, 
I want to see a nice logo when logging in, to be reassured that the app is legit
so that I have confidence in authorising it to access my personal details.

# Todo

+ [x] Replace the _temporary_ (_space invader_) logo with a more user-friendly one (_see below_)
+ [ ] Discuss Logo requirements.
  e.g: should the @dwyl Library include the @dwyl logo? 
 Are we trying to build a **_general_ purpose standalone** app that _anyone_ can use to manage their books ***or*** are we building an app for _us_ to use [@home](https://github.com/dwyl/home) ?
+ [ ] Source or commission a _real_ logo.

After a bit of searching (_the GitHub UI is not great for re-discovering infrequent use features ..._)
https://github.com/organizations/dwyl/settings/applications/612063
![image](https://user-images.githubusercontent.com/194400/60160055-6d19e380-97ec-11e9-8723-9c5846bafc7e.png)
![image](https://user-images.githubusercontent.com/194400/60160068-77d47880-97ec-11e9-8942-1f6dd8afee21.png)

Found random image of books: https://www.google.com/search?tbm=isch&q=book+logo+free
![image](https://user-images.githubusercontent.com/194400/60160469-53c56700-97ed-11e9-8394-e33261ce2f6e.png)

Removed noise:
![teal-books](https://user-images.githubusercontent.com/194400/60160521-7192cc00-97ed-11e9-9f35-a28a05589bb7.png)

Replaced default logo with one that looks more "real":
![image](https://user-images.githubusercontent.com/194400/60160584-91c28b00-97ed-11e9-9c5f-b45610318d87.png)

Now GitHub Auth looks like this:
![image](https://user-images.githubusercontent.com/194400/60160598-9a1ac600-97ed-11e9-9157-e4ec6a993b81.png)

Still think we should create/commission a _real_ logo, but this one is "OK" in the mean time.

**Comment by iteles** [comment]
I would suggest we add the dwyl logo to the cover of the top book for now and remove it when this is less dwyl-specific 😊

**Comment by nelsonic** [comment]
@iteles adding the @dwyl logo to the stack of books _could_ be a basic "fiver" or "upwork" task 
to test graphic designer for Pete's work ... 💭

**Comment by Dana94** [comment]
@iteles @nelsonic How about the dwyl logo created from the spines of books? Not sure if this is what you're going for. 

https://drive.google.com/file/d/1VDlq_nHSzWEGH9g2nWA6RYszMBHCoYX9/view?usp=sharing
