### ISSUE TITLE
Lotsa Warnings ... ⚠️

### ISSUE THREAD

**Issue by nelsonic** [dwyl/library#85]
When running (compiling) the project on `localhost` using `Elixir 1.8.1` we see _many_ warnings ...
![image](https://user-images.githubusercontent.com/194400/60166464-27afe300-97f9-11e9-9741-4292b1d039c0.png)

_Most_ (_if not all_) of these are due to the underlying libraries `Phoenix`, `Ecto`, `Poison`, etc. being out-of-date. So we need to run [`mix deps.update`](https://tosbourn.com/keeping-elixir-packages-updated/) and fix any broken tests. 

# Todo
+ [ ] Update all Elixir/Phoenix packages to latest versions
+ [ ] Fix any broken tests
+ [ ] ideally we should have ` --warnings-as-errors` enabled in a project that is kept up-to-date. 
That way _anyone_ working on the project will _immediately_ see when a warning appears.
It was removed in https://github.com/dwyl/library/commit/f38b2c4e43d094943182be4a89c72406994019d0 to make Travis-CI pass, but I feel it should be re-instated.

**Comment by nelsonic** [comment]
Pre-commit (credo) fails on `master`:
![image](https://user-images.githubusercontent.com/194400/60321562-0f64d300-9975-11e9-8d17-789e5f7e8893.png)

Pre-commit hook is not documented ... 😞 #87

**Comment by nelsonic** [comment]
@iteles given that this project is not in _active_ use (_yet_!) I've downgraded the priority of this issue to P2.
(_I'm busy trying to find/filter the P1's and see what needs to be done next ..._)
