### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by nelsonic** [dwyl/library#88]
```
mix coveralls
```
![image](https://user-images.githubusercontent.com/194400/60302062-cd16a400-992a-11e9-9c57-63c0863989dc.png)

_so_ close!!

# Todo

+ [ ] write the remaining tests required to reach 100%
+ [x] Run coverage on Travis
+ [ ] Add Codecov badge to `README.md`

related to Warnings #85 & Docs #87
